### ISSUE TITLE
GraalVM 21 Error: Could not find option TuneInlinerExploration.

### ISSUE THREAD

**Issue by nikolaaafunn** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#18]
```
Error parsing Graal options: Could not find option TuneInlinerExploration
Error: A fatal exception has occurred. Program will exit.
```
C:/Program Files/GraalVM/graalvm-community-openjdk-21.0.2+13.1/bin/javaw.exe

Flags:
```
-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1
```

**Comment by Mukul1127** [comment]
I don't think this option exists in graalvm community edition, though why are you using it? Just grab the normal one here: https://www.graalvm.org/downloads/ or remove that argument.

**Comment by MihanDeNoob** [comment]
is -Dgraal.TuneInlinerExploration=1 important?

You stated your self: "GraalVM EE 22.3.0 fixed all known Minecraft bugs" 
But the only 22.3.0+ version was CE

**Comment by Mukul1127** [comment]
> is -Dgraal.TuneInlinerExploration=1 important?
> 
> You stated your self: "GraalVM EE 22.3.0 fixed all known Minecraft bugs" But the only 22.3.0+ version was CE

GraalVM used to have 2 versions, CE and EE, CE was always free, while EE was restricted and included extra features like `TuneInlinerExploration`. 

I believe that flag gives a small performance boost.

**Comment by Mukul1127** [comment]
Download the new GraalVM (formally EE) here: https://www.graalvm.org/downloads/

or

Grab the CE version here if you need it: https://github.com/graalvm/graalvm-ce-builds/releases/

**Comment by Mukul1127** [comment]
Sorry I didn't see you commented, Any Version before 22.3.0 has these issues, I should probably remove EE as I believe it's the same for CE.

Also for CE vs EE, theres just no point in using CE over EE unless you need GraalVM features and CE's open license

**Comment by MihanDeNoob** [comment]
No worries) 
-Dgraal.TuneInlinerExploration=1 seems to did little to no difference in performance, combined with all possible optimizations and optimization mods. 

Also you misunderstood me, im not talking about java8 in any for or shape, im talking about java17 and that fixed version (22.3.0) for mincraft is only present on CE on github. On official site latest version is 22.0.2 (For java 22). 
This means that the only viable version is CE on github, since its the only version that has minecraft issues fix. 

Core of minecraft modding is on 1.20.1 java 17, so its rather important to specify CE 22.3.0 in this guide 
(and about removing -Dgraal.TuneInlinerExploration=1 to make it work)

**Comment by Mukul1127** [comment]
The issues only manifest on Java 8 as explained in the guide, you can use the new GraalVM 17 without any issues.

**Comment by MihanDeNoob** [comment]
> The issues only manifest on Java 8 as explained in the guide, you can use the new GraalVM 17 without any issues.
aaahh, i see, i guess ive missed that part. thx!
